version : '3'
services:
  magang:
    build: ./php
    image: magang_php:latest
    container_name: magang
    hostname: "magang"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db_magang
  db_magang:
    image: mariadb:10.2
    container_name: db_magang
    restart: unless-stopped
    tty: true
    ports:
      - "23306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: markocoy
      MYSQL_PASSWORD: markocoy1!.
      MYSQL_ROOT_PASSWORD: markocoy1
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx_magang:
    build: ./nginx
    image: nginx_magang:latest
    container_name: nginx_magang
    hostname: "nginx_magang"
    ports:
      - "81:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - magang